### ISSUE TITLE
Dealing with rich format caption/subtitle/footer in `print_md/html`

### ISSUE THREAD

**Issue by mattansb** [easystats/insight#508]
Would be nice if the caption/subtitle/footer could be formatted with the rich `c(words, color)` method, and have `print_md/html` ignore those.

Seems like `print_md` does ignore color, but does not parse `\n` in the subtitle?

``` r
x <- mtcars[1:5, ]

attr(x, "table_caption") <- c("Awesome Table", "blue")
attr(x, "table_subtitle") <- c("\n!!!", "red")
attr(x, "table_footer") <- list(c("\n- Thing 1", "green"),c("\n- Thing 2", "green"))

insight::export_table(x)
#> Awesome Table 
#> !!!
#> 
#>   mpg | cyl | disp |  hp | drat |   wt |  qsec | vs | am | gear | carb
#> ----------------------------------------------------------------------
#> 21.00 |   6 |  160 | 110 | 3.90 | 2.62 | 16.46 |  0 |  1 |    4 |    4
#> 21.00 |   6 |  160 | 110 | 3.90 | 2.88 | 17.02 |  0 |  1 |    4 |    4
#> 22.80 |   4 |  108 |  93 | 3.85 | 2.32 | 18.61 |  1 |  1 |    4 |    1
#> 21.40 |   6 |  258 | 110 | 3.08 | 3.21 | 19.44 |  1 |  0 |    3 |    1
#> 18.70 |   8 |  360 | 175 | 3.15 | 3.44 | 17.02 |  0 |  0 |    3 |    2
#> 
#> - Thing 1
#> - Thing 2
```

![image](https://user-images.githubusercontent.com/35330040/154834323-bdfb7878-f082-45a7-ba1d-2c3d3ff0635c.png)

**Comment by strengejacke** [comment]
I'm not so familiar with markdown, I think you can't have subtitles? @vincentarelbundock do you know more?

**Comment by strengejacke** [comment]
to please you a bit, I have implemented this nice feature:

``` r
insight::export_table(head(iris))
#> Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | Species
#> -----------------------------------------------------------------
#>         5.10 |        3.50 |         1.40 |        0.20 |  setosa
#>         4.90 |        3.00 |         1.40 |        0.20 |  setosa
#>         4.70 |        3.20 |         1.30 |        0.20 |  setosa
#>         4.60 |        3.10 |         1.50 |        0.20 |  setosa
#>         5.00 |        3.60 |         1.40 |        0.20 |  setosa
#>         5.40 |        3.90 |         1.70 |        0.40 |  setosa

insight::export_table(head(iris), cross = "+")
#> Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | Species
#> -------------+-------------+--------------+-------------+--------
#>         5.10 |        3.50 |         1.40 |        0.20 |  setosa
#>         4.90 |        3.00 |         1.40 |        0.20 |  setosa
#>         4.70 |        3.20 |         1.30 |        0.20 |  setosa
#>         4.60 |        3.10 |         1.50 |        0.20 |  setosa
#>         5.00 |        3.60 |         1.40 |        0.20 |  setosa
#>         5.40 |        3.90 |         1.70 |        0.40 |  setosa
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
FWIW, I'm not aware of a "standard" syntax in markdown for subtitles.

I'm sure one of the billions of markdown "flavours" has one, but I try use a different format for complicated stuff.

**Comment by mattansb** [comment]
> I'm not so familiar with markdown, I think you can't have subtitles?

I don't this so either - but we can have some unofficual format, to have titles auto wrapped in `***Caption***` and subtitles in `*Subtitle*`, so we'd in the example above:

> ***Awesome Table***
*!!!*

(without the trailing "blue" and "red", naturally.)

**Comment by strengejacke** [comment]
But I'm using `Table:`, which creates proper table headers (indexed) in markdown. This would get lost...

**Comment by vincentarelbundock** [comment]
FWIW, I think this functionality is useful for printouts, but creating complex markdown tables with lots of customization options should probably be another package's job.

**Comment by strengejacke** [comment]
At least the HTML issue should be resolved now.

**Comment by bwiernik** [comment]
Pandoc markdown is the only flavor we really need to worry about. That doesn't have table subtitles

**Comment by strengejacke** [comment]
@mattansb any objections? else, we could close this issue, the other points have been addressed.

**Comment by mattansb** [comment]
Thanks @strengejacke !

I'm still seeing the caption and subtitle on the same row for Markdown, any way to fix that?

![image](https://user-images.githubusercontent.com/35330040/154904639-eb04e559-4432-4a51-9f08-76cc71a46766.png)

**Comment by strengejacke** [comment]
> I'm still seeing the caption and subtitle on the same row for Markdown, any way to fix that?

See discussion above. There is no markdown flavor (at least none that is important to us) that supports subtitles, and using different formatting (like bold and italic in two lines) would require to remove the feature of using the `Table` tag, which gives you properly rendered table titles that are also indexed in the document. That's why the "majority" of comments suggests not supporting subtitles for markdown.

**Comment by mattansb** [comment]
Got it, thanks!
